In [ ]:
import pandas as pd
alunosDIC = {'Nome':['Ricardo', 'Pedro', 'Roberto', 'Carlos'],
          'Nota':[4, 7, 5.5, 9],
          'Aprovado':['Não', 'Sim','Não', 'Sim']}

In [ ]:
alunosDF = pd.DataFrame(alunosDIC)

NameError: name 'pd' is not defined

In [ ]:
print(alunosDF)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim

In [ ]:
alunosDF['Nome']

0    Ricardo
1      Pedro
2    Roberto
3     Carlos
Name: Nome, dtype: str

In [ ]:
alunosDF.loc[0:2]

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não

In [ ]:
alunosDF.loc[alunosDF['Nota']>=7]

     Nome  Nota Aprovado
1   Pedro   7.0      Sim
3  Carlos   9.0      Sim